### ISSUE TITLE
What is 'packetRawData' in main.m?

### ISSUE THREAD

**Issue by askia318** [JonathanTSilva/cavitation#1]
in you main.m, load the data (maybe dataxxx.mat) first, but what is the variable 'packetRawData'? thanks

**Comment by JonathanTSilva** [comment]
Hi @askia318,

The `packageRawData` is obtained when you run the `Main.m` script with some raw data loaded by:

```matlab
%1- Load Database:
fileName = "00-0";
file = sprintf("%s.mat", fileName);
folder = "..\Dados\Oficial\mat\100cm\";
dir = strcat(folder,file);
load(dir);
```

These .mat files aren't loaded here, but I'll load some samples for you to test there. Basically, they consist of samples obtained from the PROFINET network (S71200 and Simocode Pro V PN) with an update of 1ms in a range of 1s, resulting in 60000 data. As they are obtained using the Wireshark sniffer, they have a .pcap extension; however, as matlab does not read data of this type, a converter developed at my Institute was used, which converts .pcap files to .mat ([LINK][http://pcap2mat.ti.srt.ifsp.edu.br/pcap2mat/]).

So, these files initially loaded in Main.m for initial data processing, load the variable `packageRawData`, as can be seen in the figures below:

Workspace             |  Variables - packageRawData
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/58694273/135347583-78386003-5518-408c-a6e4-fd69e15eec32.png)  |  ![]![image](https://user-images.githubusercontent.com/58694273/135347617-e756323c-a1e6-4b4e-ba6b-7deb81fde368.png)

I'll put in a sample of data and change the code to read it. 
I hope it helped you! 
Best Regards.
